# Generated by Django 2.1.3 on 2018-11-21 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_auto_20181121_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
