# Generated by Django 2.1.3 on 2018-11-21 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_auto_20181121_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 10, 28, 33, 896074)),
        ),
    ]
