# Generated by Django 2.1.3 on 2018-11-21 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0008_auto_20181121_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 10, 31, 7, 407399)),
        ),
    ]
